MONGODB_HOST: mongodb-{{ env }}.lakshmimopidevi.fun # mongodb-dev.lakshmimopidevi.fun
REDIS_HOST: redis-{{ env }}.lakshmimopidevi.fun
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.lakshmimopidevi.fun
CART_HOST: cart.backend-alb-{{ env }}.lakshmimopidevi.fun
USER_HOST: user.backend-alb-{{ env }}.lakshmimopidevi.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.lakshmimopidevi.fun
MYSQL_HOST: mysql-{{ env }}.lakshmimopidevi.fun
SHIPPING_HOST: shipping.backend-alb-{{ env }}.lakshmimopidevi.fun
PAYMENT_HOST: payment.backend-alb-{{ env }}.lakshmimopidevi.fun